name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://git.drupalcode.org/project/sensitive_content"
      env:
        GITLAB_HOSTNAME: "git.drupal.org"
        GITLAB_USERNAME: "project_169619_bot_5ef740282e5913b658eb7eb092e3ef4d"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "169619"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}